# DataFrame Basics

This notebook covers the fundamental concepts of Pandas DataFrames, including creation, indexing, attributes, statistical analysis, and practical operations.

---

## 1. Creating DataFrames

In [1]:
import pandas as pd
import numpy as np

# --- Creating DataFrame from Series ---
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({1: s1, 2: s2})
print("DataFrame from 2 Series:")
display(df)
print("Column type:", type(df[1]))

# --- Creating DataFrame from a Dictionary ---
df = pd.DataFrame({
    "name": ["a", "a", "b", "c", "d", "e"],
    "age": [15, 15, 17, 20, 26, 30],
    "score": [60.5, 60.5, 80, 30.6, 70, 83.5]
}, index=[1, 2, 3, 4, 5, 6], columns=["name", "score", "age"])

print("\n" + "="*40)
print("Final DataFrame:")
display(df)

DataFrame from 2 Series:

   1   2
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

Column type: <class 'pandas.Series'>

========================================
Final DataFrame:

  name  score  age
1    a   60.5   15
2    a   60.5   15
3    b   80.0   17
4    c   30.6   20
5    d   70.0   26
6    e   83.5   30

## 2. DataFrame Attributes

In [2]:
print("Index:", df.index)
print("Columns:", df.columns)
print("Values:\n", df.values)
print("-" * 30)

print("ndim (dimensions):", df.ndim)
print("shape (rows, cols):", df.shape)
print("size (total elements):", df.size)
print("dtypes:\n", df.dtypes)

Index: Index([1, 2, 3, 4, 5, 6], dtype='int64')
Columns: Index(['name', 'score', 'age'], dtype='str')
Values:
 [['a' 60.5 15]
 ['a' 60.5 15]
 ['b' 80.0 17]
 ['c' 30.6 20]
 ['d' 70.0 26]
 ['e' 83.5 30]]
------------------------------
ndim (dimensions): 2
shape (rows, cols): (6, 3)
size (total elements): 18
dtypes:
 name         str
score    float64
age        int64
dtype: object

## 3. Indexing: Rows (`loc` vs `iloc`)

In [3]:
# Accessing rows
print("df.loc[4] (Row with label 4):")
print(df.loc[4])
print("\ndf.iloc[3] (Row at integer position 3):")
print(df.iloc[3]) # Outputs the same as row 4 in this example

df.loc[4] (Row with label 4):
name        c
score    30.6
age        20
Name: 4, dtype: object

df.iloc[3] (Row at integer position 3):
name        c
score    30.6
age        20
Name: 4, dtype: object

## 4. Column Access and Single Value Retrieval

In [4]:
# Accessing a single column (returns a Series)
print("df.loc[:, 'name']:")
print(df.loc[:, "name"])
print("\ndf.iloc[:, 0] (First column by position):")
print(df.iloc[:, 0])

print("-" * 30)

# Getting single scalar values
print("df.at[3, 'score']:", df.at[3, 'score'])  # Access by label
print("df.iat[2, 1]:", df.iat[2, 1])            # Access by integer position (Row 2, Col 1)
print("df.loc[3, 'score']:", df.loc[3, 'score'])
print("df.iloc[2, 1]:", df.iloc[2, 1])

df.loc[:, 'name']:
1    a
2    a
3    b
4    c
5    d
6    e
Name: name, dtype: str

df.iloc[:, 0] (First column by position):
1    a
2    a
3    b
4    c
5    d
6    e
Name: name, dtype: str
------------------------------
df.at[3, 'score']: 80.0
df.iat[2, 1]: 80.0
df.loc[3, 'score']: 80.0
df.iloc[2, 1]: 80.0

### 4.1 Accessing Columns: `df['col']` vs `df[['col']]`

In [5]:
# Single bracket returns a Series
print("df['name'] (Series):")
print(df['name'])
print("Type:", type(df['name']))

print("\ndf.name (Series - attribute style):")
print(df.name)

print("\ndf[['name']] (DataFrame with single column):")
print(df[['name']])

df['name'] (Series):
1    a
2    a
3    b
4    c
5    d
6    e
Name: name, dtype: str
Type: <class 'pandas.Series'>

df.name (Series - attribute style):
1    a
2    a
3    b
4    c
5    d
6    e
Name: name, dtype: str

df[['name']] (DataFrame with single column):
  name
1    a
2    a
3    b
4    c
5    d
6    e

## 5. Exploring Data: Head, Tail, and Sampling

In [6]:
print("df.head(2):")
print(df.head(2))
print("\ndf.tail(3):")
print(df.tail(3))
print("\ndf.sample(3) (Randomly select 3 rows):")
print(df.sample(3))

df.head(2):
  name  score  age
1    a   60.5   15
2    a   60.5   15

df.tail(3):
  name  score  age
4    c   30.6   20
5    d   70.0   26
6    e   83.5   30

df.sample(3) (Randomly select 3 rows):
  name  score  age
5    d   70.0   26
3    b   80.0   17
6    e   83.5   30

## 6. Boolean Masking and Conditional Filtering

In [7]:
# Boolean mask: Score > 70
print("Boolean mask (df.score > 70):")
print(df.score > 70)

# Compound mask: Score > 70 and Age < 30
print("\nFiltered rows (Score > 70 & Age < 30):")
print(df[(df["score"] > 70) & (df.age < 30)])

print("\nCheck if values are in list ['b', 20]:")
print(df.isin(['b', 20]))
print("\nCheck for NaN values:")
print(df.isna())

Boolean mask (df.score > 70):
1    False
2    False
3     True
4    False
5    False
6     True
Name: score, dtype: bool

Filtered rows (Score > 70 & Age < 30):
  name  score  age
3    b   80.0   17

Check if values are in list ['b', 20]:
    name  score    age
1  False  False  False
2  False  False  False
3   True  False  False
4  False  False   True
5  False  False  False
6  False  False  False

Check for NaN values:
    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False

## 7. Descriptive Statistics and Aggregations

In [8]:
print("Sum of scores:", df['score'].sum())
print("Max score:", df['score'].max())
print("Min age:", df.age.min())
print("Mean score:", df['score'].mean())
print("Median score:", df['score'].median())
print("Mode of age:", df['age'].mode())
print("-" * 30)

print("Std dev of score:", df.score.std())
print("Variance of score:", df.score.var())
print("25th Percentile of score:", df.score.quantile(0.25))
print("-" * 30)

print("Full descriptive statistics:")
print(df.describe())
print("\nCount of non-null values per column:")
print(df.count())

print("\nValue counts (all columns together):")
print(df.value_counts())

Sum of scores: 385.1
Max score: 83.5
Min age: 15
Mean score: 64.18333333333334
Median score: 65.25
Mode of age: 0    15
Name: age, dtype: int64
------------------------------
Std dev of score: 19.037375519400424
Variance of score: 362.4216666666666
25th Percentile of score: 60.5
------------------------------
Full descriptive statistics:
           score        age
count   6.000000   6.000000
mean   64.183333  20.500000
std    19.037376   6.220932
min    30.600000  15.000000
25%    60.500000  15.500000
50%    65.250000  18.500000
75%    77.500000  24.500000
max    83.500000  30.000000

Count of non-null values per column:
name     6
score    6
age      6
dtype: int64

Value counts (all columns together):
name  score  age
a     60.5   15     2
b     80.0   17     1
c     30.6   20     1
d     70.0   26     1
e     83.5   30     1
Name: count, dtype: int64

## 8. Deduplication and Data Transformation

In [9]:
print("DataFrame after dropping exact duplicate rows:")
print(df.drop_duplicates())

print("\nDuplicates based on 'age' column:")
print(df.duplicated(subset=['age']))

print("-" * 30)

# Replacing values
print("Replace age 15 with 39:")
print(df.replace(15, 39))

# Cumulative operations
print("\nCumulative max (score):")
display(df.cummax(axis=0))

DataFrame after dropping exact duplicate rows:
  name  score  age
1    a   60.5   15
3    b   80.0   17
4    c   30.6   20
5    d   70.0   26
6    e   83.5   30

Duplicates based on 'age' column:
1    False
2     True
3    False
4    False
5    False
6    False
dtype: bool
------------------------------
Replace age 15 with 39:
  name  score  age
1    a   60.5   39
2    a   60.5   39
3    b   80.0   17
4    c   30.6   20
5    d   70.0   26
6    e   83.5   30

Cumulative max (score):

  name  score  age
1    a   60.5   15
2    a   60.5   15
3    b   80.0   17
4    c   80.0   20
5    d   80.0   26
6    e   83.5   30

## 9. Sorting and Selecting Top Rows

In [10]:
print("Sort by index (Descending):")
print(df.sort_index(ascending=False))

print("\nSort by multiple columns (Score Asc, Age Desc):")
print(df.sort_values(by=['score', 'age'], ascending=[True, False]))

print("\nTop 2 scores overall (nlargest):")
print(df.nlargest(2, columns=['score', 'age']))

print("\nBottom 2 scores overall (nsmallest):")
print(df.nsmallest(2, columns=['score', 'age']))

Sort by index (Descending):
  name  score  age
6    e   83.5   30
5    d   70.0   26
4    c   30.6   20
3    b   80.0   17
2    a   60.5   15
1    a   60.5   15

Sort by multiple columns (Score Asc, Age Desc):
  name  score  age
4    c   30.6   20
1    a   60.5   15
2    a   60.5   15
5    d   70.0   26
3    b   80.0   17
6    e   83.5   30

Top 2 scores overall (nlargest):
  name  score  age
6    e   83.5   30
3    b   80.0   17

Bottom 2 scores overall (nsmallest):
  name  score  age
4    c   30.6   20
1    a   60.5   15

## 10. Practical Case Study: Student Scores Analysis

In [11]:
data = {
    'name': ['a', 'b', 'c', 'd', 'e'],
    'math': [85, 92, 78, 88, 95],
    'english': [90, 88, 85, 92, 80],
    'physics': [75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)

print("Raw student scores:")
display(scores)

# Adding new columns
scores['sum'] = scores[['math', 'english', 'physics']].sum(axis=1)
scores['average'] = scores[['math', 'english', 'physics']].mean(axis=1)

print("\nDataFrame with 'sum' and 'average' columns:")
display(scores)

print("\nFilter: Math > 90 OR English > 60:")
display(scores[(scores['math'] > 90) | (scores['english'] > 60)])

print("\nTop 3 students by total score:")
print(scores.sort_values('sum', ascending=False).head(3))

# Alternative way to find top 3
print("\nTop 3 students using nlargest:")
print(scores.nlargest(3, columns=['sum']))

Raw student scores:

  name  math  english  physics
0    a    85       90       75
1    b    92       88       80
2    c    78       85       88
3    d    88       92       85
4    e    95       80       90

DataFrame with 'sum' and 'average' columns:

  name  math  english  physics  sum    average
0    a    85       90       75  250  83.333333
1    b    92       88       80  260  86.666667
2    c    78       85       88  251  83.666667
3    d    88       92       85  265  88.333333
4    e    95       80       90  265  88.333333

Filter: Math > 90 OR English > 60:

  name  math  english  physics  sum    average
0    a    85       90       75  250  83.333333
1    b    92       88       80  260  86.666667
2    c    78       85       88  251  83.666667
3    d    88       92       85  265  88.333333
4    e    95       80       90  265  88.333333

Top 3 students by total score:
  name  math  english  physics  sum    average
4    e    95       80       90  265  88.333333
3    d    88       92       85  265  88.333333
1    b    92       88       80  260  86.666667

Top 3 students using nlargest:
  name  math  english  physics  sum    average
3    d    88       92       85  265  88.333333
4    e    95       80       90  265  88.333333
1    b    92       88       80  260  86.666667

## 11. Practical Case Study: Product Sales

In [12]:
data = {
    'product': ['A', 'B', 'C', 'D'],
    'price': [100, 150, 200, 120],
    'num': [50, 30, 20, 40]
}
df = pd.DataFrame(data)

# Calculate total revenue for each product
df['total'] = df['price'] * df['num']

print("Product sales list with total revenue:")
display(df)

print("\nBest selling product by total revenue:")
print(df.nlargest(1, columns=['total']))

print("\nFull list sorted by total revenue (Descending):")
print(df.sort_values('total', ascending=False))

Product sales list with total revenue:

  product  price  num  total
0       A    100   50   5000
1       B    150   30   4500
2       C    200   20   4000
3       D    120   40   4800

Best selling product by total revenue:
  product  price  num  total
0       A    100   50   5000

Full list sorted by total revenue (Descending):
  product  price  num  total
0       A    100   50   5000
3       D    120   40   4800
1       B    150   30   4500
2       C    200   20   4000