# Data Analysis Basics

## 1. Data Import and Export (CSV / JSON)

In [40]:
import pandas as pd
import numpy as np
import os
import json

# Check current working directory
print("Current working directory:", os.getcwd())

# --- Load and inspect CSV ---
df = pd.read_csv('../data/employees.csv')
print("Data type:", type(df))
print("\nLast 5 rows:")
print(df.tail())
print("\nAverage salary:", df.salary.mean())

# Save last 5 rows to a new CSV file
df.tail().to_csv('../data/new.csv')
print("\nCSV file saved to '../data/new.csv'")

Current working directory: C:\Users\DELL\python_data_analysis\notebooks
Data type: <class 'pandas.DataFrame'>

Last 5 rows:
     employee_id first_name last_name     email  phone_number      job_id  \
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
102   6000.0             NaN       201.0           20.0
103   6500.0             NaN       101.0           40.0
104  10000.0             NaN       101.0           70.0
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0

Average salary: 6461.682242990654

CSV file saved to '../data/new.csv'

In [41]:
# --- Load JSON data ---
df = pd.read_json('../data/data1.json')
print("DataFrame loaded from JSON:")
display(df)

# Read raw JSON as Python dict to compare
with open('../data/data1.json', encoding='utf-8') as f:
    data = json.load(f)
print("\nRaw JSON data type:", type(data))
print("Raw JSON data structure:", data)

DataFrame loaded from JSON:

   id name  age
0   1   张三   25
1   2   李四   30
2   3   王五   28

Raw JSON data type: <class 'list'>
Raw JSON data structure: [{'id': 1, 'name': '张三', 'age': 25}, {'id': 2, 'name': '李四', 'age': 30}, {'id': 3, 'name': '王五', 'age': 28}]

## 2. Missing Values Detection and Imputation

In [42]:
# --- Test different kinds of missing values ---
s = pd.Series([1, 2, np.nan, None, pd.NA])
print("Series with mixed missing values:")
print(s)
print("\nCheck NaN (isna()):")
print(s.isna())
print("Sum of NaNs:", s.isna().sum())

print("-" * 40)

# --- Load weather dataset with NaNs ---
weather_withna = pd.read_csv('../data/weather_withna.csv', sep=',')
print("Weather dataset preview:")
display(weather_withna)

print("\nSum of NaNs per column:")
print(weather_withna.isna().sum())

# --- Methods to handle missing values ---
print("\nDrop rows where ALL values are NaN (how='all'):")
print(weather_withna.dropna(how='all').tail())

print("\n--- Fill with fixed values (temp_max=20, wind=2.5) ---")
print(weather_withna.fillna({'temp_max': 20, 'wind': 2.5}).tail())

print("\n--- Fill with the column mean ---")
print(weather_withna.fillna(weather_withna[['temp_max', 'wind']].mean()).tail())

print("\n--- Forward Fill (ffill) - Use previous row's valid value ---")
print(weather_withna.ffill().tail())

print("\n--- Backward Fill (bfill) - Use next row's valid value ---")
print(weather_withna.bfill().tail())

Series with mixed missing values:
0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object

Check NaN (isna()):
0    False
1    False
2     True
3     True
4     True
dtype: bool
Sum of NaNs: 3
----------------------------------------
Weather dataset preview:

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            NaN       NaN       NaN   NaN      NaN
1457  2015-12-28            NaN       NaN       NaN   NaN      NaN
1458  2015-12-29            NaN       NaN       NaN   NaN      NaN
1459  2015-12-30            NaN       NaN       NaN   NaN      NaN
1460  2015-12-31           20.6      12.2       5.0   3.8     rain

[1461 rows x 6 columns]

Sum of NaNs per column:
date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64

Drop rows where ALL values are NaN (how='all'):
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN       NaN       NaN   NaN     NaN
1457  2015-12-28            NaN       NaN       NaN   NaN     NaN
1458  2015-12-29            NaN       NaN       NaN   NaN     NaN
1459  2015-12-30            NaN       NaN       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

--- Fill with fixed values (temp_max=20, wind=2.5) ---
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

--- Fill with the column mean ---
            date  precipitation   temp_max  temp_min      wind weather
1456  2015-12-27            NaN  15.851468       NaN  3.242055     NaN
1457  2015-12-28            NaN  15.851468       NaN  3.242055     NaN
1458  2015-12-29            NaN  15.851468       NaN  3.242055     NaN
1459  2015-12-30            NaN  15.851468       NaN  3.242055     NaN
1460  2015-12-31           20.6  12.200000       5.0  3.800000    rain

--- Forward Fill (ffill) - Use previous row's valid value ---
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

--- Backward Fill (bfill) - Use next row's valid value ---
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

## 3. Deduplication, Data Types and Binning

In [43]:
# --- Duplicates ---
data = {
    "name": ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    "age": [26, 25, 30, 25, 35, 30],
    'city': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)
print("Original dataframe:")
display(df)

print("\nCheck duplicates:")
print(df.duplicated())
print("\nDrop duplicates based on 'name' (keeping first):")
print(df.drop_duplicates(subset=['name']))

print("-" * 40)

# --- Type Conversion & Mapping ---
df = pd.read_csv('../data/sleep.csv')

# Convert dtype to category
df['gender'] = df['gender'].astype('category')
print("Gender column dtype after conversion:")
print(df['gender'].dtype)

# Create a boolean category mapping
df['is_male'] = df['gender'].map({'Female': True, 'Male': False})
print("\nMapped column 'is_male':")
print(df['is_male'].head())

# --- Discretization (Binning) with salary data ---
df_emp = pd.read_csv('../data/employees.csv')
df1 = df_emp.head(10)[['employee_id', 'salary']]

# Cut into 3 equal-width bins
print("\nSalary bins (equal width):")
print(pd.cut(df1['salary'], bins=3).value_counts())

# Cut with custom bins labels
df1['salary_level'] = pd.cut(df1['salary'], bins=[0, 10000, 20000, 30000],
                               labels=['Low', 'Medium', 'High'])
print("\nSalary level categories (Custom bins):")
print(df1['salary_level'])

Original dataframe:

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

Check duplicates:
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

Drop duplicates based on 'name' (keeping first):
    name  age city
0  alice   26   NY
2    bob   30   LA
4   jack   35   SF
----------------------------------------
Gender column dtype after conversion:
category

Mapped column 'is_male':
0    False
1     True
2    False
3    False
4    False
Name: is_male, dtype: category
Categories (2, bool): [True, False]

Salary bins (equal width):
salary
(4180.2, 10800.0]     6
(10800.0, 17400.0]    3
(17400.0, 24000.0]    1
Name: count, dtype: int64

Salary level categories (Custom bins):
0      High
1    Medium
2    Medium
3       Low
4       Low
5       Low
6       Low
7       Low
8    Medium
9       Low
Name: salary_level, dtype: category
Categories (3, str): ['Low' < 'Medium' < 'High']

## 4. Reshaping Data: Melt, Pivot, and String Splitting

In [44]:
# --- Wide to Long (Melt) ---
data = {
    'ID': [1, 2],
    'name': ['alice', 'bob'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
print("Original Wide Format:")
display(df)

# Melt
df2 = pd.melt(df, id_vars=['ID', 'name'], var_name='subject', value_name='note')
df2 = df2.sort_values('name')
print("\nMelted to Long Format:")
print(df2)

# Pivot back to Wide
print("\nPivot back to Wide Format:")
display(pd.pivot(df2, index='ID', columns='subject', values='note'))

print("-" * 40)

# --- String Splitting ---
df_sleep = pd.read_csv('../data/sleep.csv')
df_bp = df_sleep[['person_id', 'blood_pressure']].copy()

# Split blood_pressure '120/80' into '120' and '80'
df_bp[['high', 'low']] = df_bp['blood_pressure'].str.split('/', expand=True)
df_bp['high'] = df_bp['high'].astype('int64')
df_bp['low'] = df_bp['low'].astype('int64')

print("Blood Pressure split into high/low integers:")
print(df_bp.head())

Original Wide Format:

   ID   name  Math  English  Science
0   1  alice    90       88       95
1   2    bob    85       92       89

Melted to Long Format:
   ID   name  subject  note
0   1  alice     Math    90
2   1  alice  English    88
4   1  alice  Science    95
1   2    bob     Math    85
3   2    bob  English    92
5   2    bob  Science    89

Pivot back to Wide Format:

subject  English  Math  Science
ID
1             88    90       95
2             92    85       89

----------------------------------------
Blood Pressure split into high/low integers:
   person_id blood_pressure  high  low
0          1         124/70   124   70
1          2         131/86   131   86
2          3         122/70   122   70
3          4         124/72   124   72
4          5         133/78   133   78

## 5. Time Series Processing (Timestamps and Resampling)

In [45]:
# --- Timestamp properties ---
d = pd.Timestamp('2015-05-02 10:22')
print("Timestamp:", d)
print("Type:", type(d))
print(f"Year: {d.year}, Quarter: {d.quarter}, Month: {d.month}, Day: {d.day}")
print(f"Hour: {d.hour}, Minute: {d.minute}, Second: {d.second}")
print("Is end of month:", d.is_month_end)
print("Day of the week (Monday=0):", d.day_of_week)
print("Day name:", d.day_name())

print("-" * 40)

# --- Resampling Weather Data ---
df_weather = pd.read_csv('../data/weather.csv', parse_dates=['date'])
df_weather.set_index('date', inplace=True)

print("Monthly average temperatures (using 'ME' - Month End):")
display(df_weather[["temp_max", "temp_min"]].resample("ME").mean())

print("Monthly average temperatures (using 'MS' - Month Start):")
display(df_weather[["temp_max", "temp_min"]].resample("MS").mean())

# --- Generating Date Ranges ---
days = pd.date_range("2025-07-03", periods=10, freq="W")
print("\nGenerated weekly date range:")
print(days)

Timestamp: 2015-05-02 10:22:00
Type: <class 'pandas.Timestamp'>
Year: 2015, Quarter: 2, Month: 5, Day: 2
Hour: 10, Minute: 22, Second: 0
Is end of month: False
Day of the week (Monday=0): 5
Day name: Saturday
----------------------------------------
Monthly average temperatures (using 'ME' - Month End):

             temp_max   temp_min
date
2012-01-31   7.054839   1.541935
2012-02-29   9.275862   3.203448
2012-03-31   9.554839   2.838710
2012-04-30  14.873333   5.993333
2012-05-31  17.661290   8.190323
2012-06-30  18.693333  10.480000
2012-07-31  22.906452  12.932258
2012-08-31  25.858065  14.009677
2012-09-30  22.880000  11.243333
2012-10-31  15.829032   8.380645
2012-11-30  11.326667   5.226667
2012-12-31   7.235484   3.293548
2013-01-31   6.106452   0.796774
2013-02-28   9.467857   4.325000
2013-03-31  12.709677   4.977419
2013-04-30  14.243333   6.696667
2013-05-31  19.625806   9.922581
2013-06-30  23.253333  13.163333
2013-07-31  26.093548  13.932258
2013-08-31  26.119355  15.480645
2013-09-30  21.360000  13.590000
2013-10-31  14.229032   7.638710
2013-11-30  12.053333   5.590000
2013-12-31   7.022581   1.570968
2014-01-31   9.600000   4.096774
2014-02-28   8.200000   2.635714
2014-03-31  12.906452   5.425806
2014-04-30  15.460000   6.730000
2014-05-31  19.870968  10.216129
2014-06-30  21.590000  11.756667
2014-07-31  26.900000  14.425806
2014-08-31  26.383871  14.893548
2014-09-30  23.163333  13.233333
2014-10-31  17.961290  10.883871
2014-11-30  11.030000   4.510000
2014-12-31  10.138710   4.609677
2015-01-31  10.154839   4.351613
2015-02-28  12.517857   6.085714
2015-03-31  14.377419   6.193548
2015-04-30  15.503333   6.030000
2015-05-31  20.025806  10.129032
2015-06-30  26.063333  13.576667
2015-07-31  28.093548  15.500000
2015-08-31  26.087097  14.693548
2015-09-30  20.293333  11.366667
2015-10-31  17.538710  10.500000
2015-11-30   9.683333   3.480000
2015-12-31   8.380645   3.825806

Monthly average temperatures (using 'MS' - Month Start):

             temp_max   temp_min
date
2012-01-01   7.054839   1.541935
2012-02-01   9.275862   3.203448
2012-03-01   9.554839   2.838710
2012-04-01  14.873333   5.993333
2012-05-01  17.661290   8.190323
2012-06-01  18.693333  10.480000
2012-07-01  22.906452  12.932258
2012-08-01  25.858065  14.009677
2012-09-01  22.880000  11.243333
2012-10-01  15.829032   8.380645
2012-11-01  11.326667   5.226667
2012-12-01   7.235484   3.293548
2013-01-01   6.106452   0.796774
2013-02-01   9.467857   4.325000
2013-03-01  12.709677   4.977419
2013-04-01  14.243333   6.696667
2013-05-01  19.625806   9.922581
2013-06-01  23.253333  13.163333
2013-07-01  26.093548  13.932258
2013-08-01  26.119355  15.480645
2013-09-01  21.360000  13.590000
2013-10-01  14.229032   7.638710
2013-11-01  12.053333   5.590000
2013-12-01   7.022581   1.570968
2014-01-01   9.600000   4.096774
2014-02-01   8.200000   2.635714
2014-03-01  12.906452   5.425806
2014-04-01  15.460000   6.730000
2014-05-01  19.870968  10.216129
2014-06-01  21.590000  11.756667
2014-07-01  26.900000  14.425806
2014-08-01  26.383871  14.893548
2014-09-01  23.163333  13.233333
2014-10-01  17.961290  10.883871
2014-11-01  11.030000   4.510000
2014-12-01  10.138710   4.609677
2015-01-01  10.154839   4.351613
2015-02-01  12.517857   6.085714
2015-03-01  14.377419   6.193548
2015-04-01  15.503333   6.030000
2015-05-01  20.025806  10.129032
2015-06-01  26.063333  13.576667
2015-07-01  28.093548  15.500000
2015-08-01  26.087097  14.693548
2015-09-01  20.293333  11.366667
2015-10-01  17.538710  10.500000
2015-11-01   9.683333   3.480000
2015-12-01   8.380645   3.825806

Generated weekly date range:
DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07'],
              dtype='datetime64[us]', freq='W-SUN')

## 6. GroupBy and Aggregation

In [46]:
df = pd.read_csv('../data/employees.csv')
# Drop rows with missing department_id and convert to int
df = df.dropna(subset=['department_id'])
df['department_id'] = df['department_id'].astype('int64')

# 1. Groups by department_id
print("Grouped departments (keys):")
print(df.groupby('department_id').groups.keys())

print("\n--- Average salary per Department ---")
df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)
display(df2)

print("\nAverage salary by Department (Sorted descending):")
print(df2.sort_values('salary', ascending=False))

print("\n--- Multi-level GroupBy (Department + Job ID) ---")
df3 = df.groupby(['department_id', 'job_id'])[['salary']].mean()
df3['salary'] = df3['salary'].round(1)
print(df3.sort_values('salary', ascending=False))

Grouped departments (keys):
dict_keys([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110])

--- Average salary per Department ---

                 salary
department_id
10              4400.00
20              9500.00
30              4150.00
40              6500.00
50              3475.56
60              5760.00
70             10000.00
80              8955.88
90             19333.33
100             8600.00
110            10150.00

Average salary by Department (Sorted descending):
                 salary
department_id
90             19333.33
110            10150.00
70             10000.00
20              9500.00
80              8955.88
100             8600.00
40              6500.00
60              5760.00
10              4400.00
30              4150.00
50              3475.56

--- Multi-level GroupBy (Department + Job ID) ---
                           salary
department_id job_id
90            AD_PRES     24000.0
              AD_VP       17000.0
20            MK_MAN      13000.0
80            SA_MAN      12200.0
100           FI_MGR      12000.0
110           AC_MGR      12000.0
30            PU_MAN      11000.0
70            PR_REP      10000.0
80            SA_REP       8396.6
110           AC_ACCOUNT   8300.0
100           FI_ACCOUNT   7920.0
50            ST_MAN       7280.0
40            HR_REP       6500.0
20            MK_REP       6000.0
60            IT_PROG      5760.0
10            AD_ASST      4400.0
50            SH_CLERK     3215.0
              ST_CLERK     2785.0
30            PU_CLERK     2780.0

## 7. Comprehensive Case Study: Penguins & Sleep Analysis

In [47]:
# --- Penguins Case ---
df_penguins = pd.read_csv('../data/penguins.csv')
print("Penguins dataset info:")
df_penguins.info()

print("\nCheck missing values:")
print(df_penguins.isna().sum())

# Drop rows with NaN
df_penguins.dropna(inplace=True)

# Create a new feature: bill ratio
df_penguins['bill_ratio'] = df_penguins['bill_length_mm'] / df_penguins['bill_depth_mm']

# Bin body mass into categories
labels = ['low', 'medium', 'high']
df_penguins['mass_level'] = pd.cut(df_penguins['body_mass_g'], bins=3, labels=labels)

print("\nBody mass distribution:")
print(df_penguins['mass_level'].value_counts())

# Aggregation by sex and island
print("\nMean body mass grouped by Sex & Island:")
display(df_penguins.groupby(['sex', 'island']).agg({
    'body_mass_g': ['mean', 'count']
}))

print("-" * 60)

# --- Sleep Data Case ---
df_sleep = pd.read_csv('../data/sleep.csv')

# Drop sleep_disorder column
df_sleep.drop(columns='sleep_disorder', inplace=True)

# Convert Categorical columns
df_sleep['gender'] = df_sleep['gender'].astype('category')
df_sleep['occupation'] = df_sleep['occupation'].astype('category')
df_sleep['bmi_category'] = df_sleep['bmi_category'].astype('category')

# Binning Age
age_labels = ['Youth', 'Middle', 'Old']
df_sleep['age_level'] = pd.cut(df_sleep['age'], bins=3, labels=age_labels)

print("BMI Category counts:")
print(df_sleep['bmi_category'].value_counts())

print("\nAggregated Sleep Statistics by Age Group & BMI Category:")
display(df_sleep.groupby(['age_level', 'bmi_category']).agg({
    'sleep_duration': 'mean',
    'sleep_quality': 'mean',
    'stress_level': 'mean'
}))

Penguins dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

Check missing values:
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

Body mass distribution:
mass_level
low       150
medium    128
high       55
Name: count, dtype: int64

Mean body mass grouped by Sex & Island:

                  body_mass_g
                         mean count
sex    island
Female Biscoe     4319.375000    80
       Dream      3446.311475    61
       Torgersen  3395.833333    24
Male   Biscoe     5104.518072    83
       Dream      3987.096774    62
       Torgersen  4034.782609    23

------------------------------------------------------------
BMI Category counts:
bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

Aggregated Sleep Statistics by Age Group & BMI Category:

                        sleep_duration  sleep_quality  stress_level
age_level bmi_category
Youth     Normal              8.100000       6.332000      4.860000
          Obese               8.250000       6.253448      5.534483
          Overweight          8.214286       6.171429      5.317460
          Underweight         7.603279       5.883607      5.426230
Middle    Normal              7.422222       6.650000      4.944444
          Obese               7.805556       6.216667      5.888889
          Overweight          8.246154       5.956410      5.974359
          Underweight         8.497500       5.907500      5.750000
Old       Normal              7.420000       4.240000      4.200000
          Obese               7.900000       5.025000      8.000000
          Overweight          8.971429       6.285714      6.714286
          Underweight        10.500000       6.200000      6.000000